---
- name: Deploy PostgreSQL on Podman
  hosts: node2
  become: true
  vars:
    postgres_container_name: "postgresql-target"
    postgres_image: "rhel9/postgresql-15"
    postgres_user: "petclinic"
    postgres_password: "petclinic"
    postgres_db: "petclinic"
    postgres_port: 5432
    postgres_data_dir: "/home/ec2-user/postgres_data"
  
  tasks:
  - name: Create data directory for PostgreSQL
    ansible.builtin.file:
      path: "{{ postgres_data_dir }}"
      state: directory
      owner: ec2-user
      mode: '0755'

  - name: Pull PostgreSQL image
    become_user: ec2-user
    ansible.builtin.command:
      cmd: podman pull {{ postgres_image }}
      creates: /var/lib/containers/storage/overlay-images/{{ postgres_image }}

  - name: Run PostgreSQL container
    become_user: ec2-user
    ansible.builtin.command:
      cmd: >
        podman run -d --network skupper --name {{ postgres_container_name }}
        -e POSTGRES_USER={{ postgres_user }}
        -e POSTGRES_PASSWORD={{ postgres_password }}
        -e POSTGRES_DB={{ postgres_db }}
        -v {{ postgres_data_dir }}:/var/lib/postgresql/data:z
